### ISSUE TITLE
Api.Get<T> method does not lend itself to supporting error responses

### ISSUE THREAD

**Issue by munkii** [Clancey/SimpleAuth#115]
Using SimpleAuth 1.0.49.0

We currently use the FitBitApi class to call the FitBit Web API. The FitBitApi inheritance model is 

FitBitApi
OAuthApi
AuthenticatedApi
Api

The Get method is implemented in Api and is a generic method

`public virtual Task<T> Get<T>(string path = null, Dictionary<string, string> queryParameters = null, Dictionary<string, string> headers = null, bool authenticated = true);`

In an example of us calling it for getting Activity\Calories for the last 7 days we use a type that will accept Calories and Date

```
public class Activity
{
    /// <summary>
    /// Gets or sets the last edited.
    /// </summary>
    [JsonProperty(PropertyName = "dateTime")]
    public string Date { get; set; }

    /// <summary>
    /// Gets or sets the calories.
    /// </summary>
    /// <value>
    /// The calories.
    /// </value>
    [JsonProperty(PropertyName = "value")]
    public int Calories { get; set; }
}

```

and call it like this

this.api.Get<Data.Models.External.Fitbit.Activity.ActivityCollection>(url);

The problem is this only works when the FitBit response is a collection of Activities, if the response is not successful the body will not have activities and that  `Converter.Deserialize<T>` will fail and throw an uncaught exception.

 As long as the StatusCode from FitBit is not 301 the [Api class will just try to deserialise the response into T.](https://github.com/Clancey/SimpleAuth/blob/3be58f39ce0a5505b5c403dffffb73e78088a1b5/src/SimpleAuth/Api/Api.cs#L256) Shouldn't it check the response first and return a failed response.

I realise that this would probably require a change to the method return type and that would be a breaking change. 

Assuming that's not going to happen what are other people's approaches? I'm thinking let the Newtonsoft.Json.JsonReaderException happen, retry then gracefully fail.

**Comment by Clancey** [comment]
It's working exactly as expected!  If you are saying, that you expect an ActivityCollection (as you specified as the return type) It's impossible to return anything else.  

What I do in these situations, is I have a base class that has the error properties that would come from the api.

```public class ApiResult {
   public string Error {get;set;}
}

public class ActivityResult : ApiResult {
   public List<Activity> Activities {get;set;}
}
```

The other option is, you can also just not pass a type to api.Get() and it will return a string.  You now have the power to deal with that to your hearts content.
