### ISSUE TITLE
FacebookApi - Null reference exception

### ISSUE THREAD

**Issue by jamesatgithub** [Clancey/SimpleAuth#15]
with latest 1.0.20 the facebookapi broken:

[0:] System.NullReferenceException: Object reference not set to an instance of an object.
  at SimpleAuth.Providers.FacebookApi.<.ctor>b__8_0 (SimpleAuth.WebAuthenticator a) [0x00007] in <filename unknown>:0 
  at SimpleAuth.OAuthApi+<PerformAuthenticate>d__31.MoveNext () [0x0023d] in <filename unknown>:0 

I tried to debug it with the source code but got a weird error location at line of 152 in Twitter.cs

**Comment by Nyrris** [comment]
I had the same last day, you need to add the library to all platforms that you are using.

**Comment by jamesatgithub** [comment]
@Nyrris, are you using the latest 1.0.20? I did upgrade it for both the Forms PCL and Xamarin.Android projects. Twitter and Google work but facebook not. (Xamarin.iOS not tried yet)

**Comment by Clancey** [comment]
Fixed: https://github.com/Clancey/SimpleAuth/commit/5c398176942cb0016a9c9c7d6d84ad8184ec0a9f

I am working on getting some UITest written to prevent future regressions

**Comment by Clancey** [comment]
Also the fix is now on Nuget.

**Comment by jamesatgithub** [comment]
Thanks, problem fixed
