### ISSUE TITLE
Google Auth by WebView will not be allowed 

### ISSUE THREAD

**Issue by jamesatgithub** [Clancey/SimpleAuth#16]
Hi As per this link Google Auth by webview will be rolled out, any plan to provide new auth for Google?

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

"The rollout schedule for the deprecation of web-views for OAuth requests to Google is as follows. Starting October 20, 2016, we will prevent new OAuth clients from using web-views on platforms with a viable alternative, and will phase in user-facing notices for existing OAuth clients. On April 20, 2017, we will start blocking OAuth requests using web-views for all OAuth clients on platforms where viable alternatives exist."

**Comment by Clancey** [comment]
It is already started! iOS and Mac already support it. I just need to finish Android.  If you want to help feel free to jump in!

iOS: https://github.com/Clancey/SimpleAuth/commit/1f0bcc8a44254657dc5c8d90c533f46bdbf91939

Mac: https://github.com/Clancey/SimpleAuth/commit/da72af7fa67982fc13b7e8343ce8d0e367f570ea

**Comment by jamesatgithub** [comment]
I saw the sample for the Xamarin.Android project, is this available for Xamarin.Forms?

**Comment by Clancey** [comment]
Yes it would the and. Do the same setup in your forms platform specific projects

**Comment by Asseks** [comment]
I got the same error on Android 6.0, It worked a week ago, but now is broken.

**Comment by Clancey** [comment]
I need to get the readme up and going for it. But it works. On Android you need to do a few extra steps. Here is the sample: https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Droid/MainActivity.cs

**Comment by Asseks** [comment]
I checked other project on Xamarin Forms. And I got this error too.
