### ISSUE TITLE
OnAccountUpdated called unnecessarily

### ISSUE THREAD

**Issue by kentcb** [Clancey/SimpleAuth#24]
I have a custom `Account` object which I parse in `GetAccountFromAuthCode`. On it I have a `CachedUser` property so I can parse my `User` object once per (re-)authentication, rather than every time `Authenticate` is called. However, I also need to clear the cached `User` whenever the account is updated, so I do this in `OnAccountUpdated`.

The problem is, [this line](https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L144) is executed regardless of whether authentication is actually performed. The `CurrentAccount` setter calls `OnAccountUpdated`, so my `CachedUser` property is cleared every time `Authenticate` is called, regardless of whether authentication takes place.

**Comment by Clancey** [comment]
So what do you consider a (re-)authentication?  Whenever you make an auth call? That causes a new auth token to be generated and set.  So is it every time you get a new auth token or refresh token?

OnAccountUpdated should fire whenever that is set. That line should not be changed.

There are a few ways you can keep track of if the Account to tell if it is new or old.  There is a property UserData on the Account class.  I use it for the Google Api.

https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Providers/Google.cs#L58-L71

You could store the previous auth/refresh token there and do a comparison against it.  If it's empty its new, or if they match. Then there was not a change in authentication.

Does that work? If not lets talk about some other options.

**Comment by kentcb** [comment]
> Whenever you make an auth call? That causes a new auth token to be generated and set
Maybe I'm misunderstanding, but I don't think this is correct. Calling `Authenticate` calls `PerformAuthenticate`, which only re-generates tokens if necessary. See [here](https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L141-L146) for the logic that bails early if the account is still valid.

That said, I just tried using `UserData` as you suggested, and with a bit of refactoring I have it correctly caching my `User` object now. Thanks!

**Comment by Clancey** [comment]
What I meant by an Auth call, was an actual authentication call to the server.  I thought you only wanted to reset the data when the account changed, not when it is still valid.  Which is what I think you are looking for, so the userdata made sense to track existing tokens/token changes.

Glad its working though.
