### ISSUE TITLE
Google login refresh token missing

### ISSUE THREAD

**Issue by antonioseric** [Clancey/SimpleAuth#25]
I got error for not getting refresh token from google when login with google second time you install app or clear data. 

I fix it by adding `&prompt=consent` in class `SimpleAuth.Providers.GoogleAuthenticator` method `GetInitialUrl` `return new Uri(uri.AbsoluteUri + "&access_type=offline&prompt=consent");`

[Reference](https://developers.google.com/identity/protocols/OpenIDConnect#refresh-tokens)

Do you have another way to fix it?

**Comment by Clancey** [comment]
I am unable to duplicate this issue. Are you on the latest version?  This sounds like a bug that was fixed a while ago.  Cookies were re-added to the webview which caused the same auth to be used again.  Also, I dont want to add &prompt=consent since it would require logging in all the time.
