### ISSUE TITLE
Sample has invalid and unneeded client secret

### ISSUE THREAD

**Issue by trevoriancox** [Clancey/SimpleAuth#28]
In samples/Sample.Droid/MainActivity.cs, the string "native" is provided in the client secret field to the GoogleApi constructor.

This results in an "invalid_client" error on iOS. The value that works is null. A secret is not applicable to a native application.

**Comment by Clancey** [comment]
Well null still isn't correct, since some people will be using web authentication not pure native implementations.  I added another constructor that doesn't require the client secret to avoid confusion.

**Comment by trevoriancox** [comment]
@Clancey You are fast! That was a huge help... all the issues I had fixed and avail via nuget, nice!
