### ISSUE TITLE
Logging out SFSafariViewController

### ISSUE THREAD

**Issue by kentcb** [Clancey/SimpleAuth#29]
I have auth against a custom back-end working with `SFSafariViewController`, but I can't find any means via which I sign the user out. Calling `ResetData` against my `OAuthApi` and then calling `Authenticate` simply opens the browser, finds the existing cookie, and immediately logs the user back in.

I understand I need to send the user to the logout endpoint for my OAuth backend. But it looks like there is no support for this in SimpleAuth. Can you please confirm?

**Comment by Clancey** [comment]
You are partially correct, your auth endpoint is automatically redirecting and handing out the token. So you would want to add a Logout method on the API, that would call the Invalidate token call to your server. Then you would call ResetData.

Or you could handle this the way google does. When you receive a login request, and you are already logged in, show them an account picker/logout screen. If they choose the account already logged in, redirect to the right URL with the token. Else log them out. I prefer this method as it prevents people from having to keep logging in.
