### ISSUE TITLE
"no method with name='getSignInIntent'"

### ISSUE THREAD

**Issue by federicoflz** [Clancey/SimpleAuth#33]
I'm getting the following when running a Release build:

no method with name='getSignInIntent' signature='(Lcom/google/android/gms/common/api/GoogleApiClient;)Landroid/content/Intent;' in class Lcom/google/android/gms/auth/api/siginin/internal/zzc;

It runs fine on Debug, but it doesn't do so in Release. 

I'm using Visual Studio 2017.

I tried without linking, without ProGuard, etc. 

Thanks!

**Comment by Clancey** [comment]
Do you want to try no linking one more time? Make sure it is on the release build. And do a rebuild.

**Comment by federicoflz** [comment]
Thanks for the fast reply!

Reopening Visual Studio, cleaning & rebuilding zillion times didn't do anything, but I just deleted all bin and obj folders throughout all my solution projects and that fixed it... 

It even works when linking sdk assemblies now.

All set!

**Comment by Clancey** [comment]
This kind of makes sense. Google has changed the underlying class structure a few times in the native Google auth lib. Xamarin is working around this issue for future versions of the lib. But for now if you get a little miss match it all blows up.

**Comment by federicoflz** [comment]
yes... it took me some time to get it working, but everything builds & run fine now. 

Just for the record, this is what I had to end up putting when enabling ProGuard on its configuration file:

-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
