### ISSUE TITLE
Google Login Bug

### ISSUE THREAD

**Issue by goranmedic** [Clancey/SimpleAuth#36]
When I use google login in my Android app, while this code executes :
 `var user = await api.Get("https://www.googleapis.com/oauth2/v1/userinfo?alt=json");`
My screen flashes 3 times and OnAppearing method gets called 3 times.
After that I'm signed in normally.
Is this normal behaviour ?
Thanks in advance.

**Comment by Clancey** [comment]
This doesn't happen with the [sample](https://github.com/Clancey/SimpleAuth/tree/master/samples/Sample.Droid).

**Comment by goranmedic** [comment]
@Clancey  yes but sample uses `google..Authenticate()` , that works for me to, can you please try it with `google.Get("https://www.googleapis.com/oauth2/v1/userinfo?alt=json");`

**Comment by Clancey** [comment]
Still works for me. Does it work for you in the sample?

**Comment by goranmedic** [comment]
It works for me too in the sample.
The problem is that in my app, 

```
        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            SimpleAuth.Native.OnActivityResult(requestCode, resultCode, data);
        }
```
is called 3 times instead of just 1, I'm not sure why.

**Comment by Clancey** [comment]
Try checking the data, see what is passed in, are the all the same?That shouldn't cause any weird artifacts.All the callbacks come from outside my realm. I can't control theOnActiviytResult

**Comment by Kevvix** [comment]
Hi,

I got the same problem (flashing 3 times) today by mistake.
I got the problem when I try to pass a "ClientSecretID" to GoogleAPI constructor like :

var ClientSecretID = "YDS2t7_w8A8SQ15P1RMVfAzy"
var api = new GoogleApi("google", GoogleClientId, ClientSecretID)

but the problem been solve when I use the hardcoder value "GoogleApi.NativeClientSecret" as :

var api = new GoogleApi("google", GoogleClientId, GoogleApi.NativeClientSecret)

Hope it can be usefull

(my English isn't as good as I want)

**Comment by goranmedic** [comment]
@Kevvix , so you're saying that I should try something like this

`
var api = new GoogleApi("google", GoogleClientId, "YDS2t7_w8A8SQ15P1RMVfAzy")`
I'll try that on Monday, thank you for your response.

**Comment by Clancey** [comment]
I will dig in a little more and see if I can find the issue.

**Comment by Clancey** [comment]
I still cannot reproduce this. I have tried exactly as you guys have said, Also there is no difference between 

`api = new GoogleApi("google", GoogleClientId)`
and 
`api = new GoogleApi("google", GoogleClientId, GoogleApi.NativeClientSecret)`

**Comment by goranmedic** [comment]
I'm not sure why it works, but it works.

Also I'm using MainPage as login page, not App.cs like sample.
Rest of the code is pretty much the same as one in the sample.

**Comment by goranmedic** [comment]
@Clancey  have you tried it like this?
```
string googleSecret = "some secret";
string GoogleClientId = "some client id";
api = new GoogleApi("google", GoogleClientId, googleSecret);
```

**Comment by Clancey** [comment]
Yes I did. Still can't duplicate. So you want to try and debug it?

**Comment by goranmedic** [comment]
@Clancey  can you explain me how can I use refresh_token to obtain new access_token once the old one expires (in 1hour) ?

**Comment by Clancey** [comment]
You don't have too. The lib shows it for you. Just make a web call or manually call API.Authenticate();

**Comment by goranmedic** [comment]
@Clancey  thank you for your response.
The problem is I'm not supposed to prompt user to login again. 
I have a periodic task that executes at some period in background and it requires account.IdToken.
Is there any way to automatically use refresh_token to obtain new tokens ?

**Comment by Clancey** [comment]
If you don't pass in the web server client secret, the native google deals with all refreshing. SimpleAuth will ask them for the new token, and sometimes they will show the UI. If you do the secret, it will auto refresh perfectly.
