### ISSUE TITLE
A task was cancelled

### ISSUE THREAD

**Issue by Fr2eman** [Clancey/SimpleAuth#41]
I have a problem with login with google. Exception throws when i am trying to login
Exception: "A task was cancelled" after i try call
```
var account = await AuthAsync(google);
```

I have tried to check example. But It throws the same exception.

**Comment by Clancey** [comment]
Is this on device or on an emulator? iOS or Android? Also, what api are you using? the standard Google Api, or did you activate the native google auth?

**Comment by Fr2eman** [comment]
Android. This issue reproduces on devices and emulator. I use standard Google Api.

```
FindViewById<Button>(Resource.Id.loginGoogleNative).Click += async (sender, e) =>
  {
         // Create an OAuth credential and use its clientId
	var clientId = "419855213697-uq56vcune334omgqi51ou7jg08i3dnb1.apps.googleusercontent.com";

	var google = new SimpleAuth.Providers.GoogleApi("google", clientId) {//, "UwQ8aUXKDpqPzH0gpJnSij3i") {
                Scopes = new [] { "https://www.googleapis.com/auth/userinfo.profile" }
        };

        var account = await AuthAsync(google);
        var user = await google.GetUserInfo();
        // .. Do something with account
};
```
```
async Task<Account> AuthAsync(OAuthApi api)
  {
        Account result = null;
	try {
		result = await api.Authenticate ();
		Toast.MakeText (this, "Successfully Authenticated!", ToastLength.Long).Show ();
	} catch (TaskCanceledException) {
		Toast.MakeText (this, "Authentication Canceled!", ToastLength.Long).Show ();
	}
        catch (Exception ex)
        {
              Console.WriteLine(ex);
              Toast.MakeText(this, "Authentication Faild!", ToastLength.Long).Show();
        }

        if (result != null)
                Console.WriteLine(await result.ToJsonAsync());

         return result;
}
```

When i am trying to login, app always throws TaskCanceledException.
When i am trying to login in second time, app crashes with message "A task was cancelled".
You can check it on your example in project.

**Comment by Clancey** [comment]
I have tried multiple times, on both Sample.Droid, and Sample.Forms.Droid.  I cannot reproduce this. Can you try debugging and see where the task canceled came from?

**Comment by brittonbeckham** [comment]
@Fr2eman I just installed the SimpleAuth tonight and am testing the Google auth and am getting this exact same issue.  Did either of you figure this out? I'm debugging on a physical device.
```
var scopes = new[]
{
	"https://www.googleapis.com/auth/userinfo.email",
	"https://www.googleapis.com/auth/userinfo.profile"
};
var api = new GoogleApi("google", "272476888206-4lulgfh45cjgqbnf3cnuddkbf3isi3so.apps.googleusercontent.com")
{
	Scopes = scopes
};
var account = await api.Authenticate();			
```

My app crashes and stack trace leads to: 
```
OAuthApi+<PerformAuthenticate>d__32.MoveNext ()
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

**Comment by Clancey** [comment]
I am unable to duplicate this, would you mind debugging the sample and let me know what is calling canceled? I can help fix it if I can duplicate it.  I do accept pull requests!

Also you should always `Try Catch` the real Authenticate call, incase the user really does cancel logging in.

**Comment by brittonbeckham** [comment]
So I am using `Clancey.SimpleAuth` 1.0.40 and `Clancey.SimpleAuth.Google.Droid` 1.0.9 -- I don't see symbols for these nugets. 

The exception is being thrown from the `OnActivityResult` method: 
`SimpleAuth.Native.OnActivityResult(requestCode, resultCode, data);`

I tried try {} catching on that line and forcing an "OK" result, but the catch block is just skipped and it still throws an unhandled exception.

**Comment by Clancey** [comment]
Sorry for debugging info, would you mind cloning the repo and running one of the Android samples? See if you can still duplicate it. They reference the source. Also on the next version I will start shipping debug symbols. That has been on my todo list for awhile.

**Comment by brittonbeckham** [comment]
Will try that now.

**Comment by brittonbeckham** [comment]
In my own app, I hit login as google, it shows me the prompt to select a Google account. I tap the account I want to login as. Then the app crashes.

However, in your sample project `Sample.Forms.Droid`, the login worked fine... I tap Google button, it shows me the prompt to select a Google account. I tap the account I want to login as. It then shows me a success alert.

**Comment by Clancey** [comment]
:(  That's the problem I have been having. I cannot duplicate it. You could try changing the secrets in the sample, and the signing so it matches. Maybe it is a config issue?

Or you can try referencing SimpleAuth from source in your app? That may lead to the exception.

**Comment by brittonbeckham** [comment]
I can try swapping the client Id/Secret... but can you tell me what `GoogleApi.NativeClientSecret` is?

**Comment by Clancey** [comment]
There isn't one. So here is how that works.  Google doesn't require the secret unless you are going to refresh the tokens yourself. (It actually works better if you pass the secret).  If you don't pass in a secret, Simple Auth handles it just fine. That variable is a temp value used to determine if you are not using a secret.

**Comment by brittonbeckham** [comment]
Ok swapping your clientId/secret with mine gives me a "user cancelled" alert. It appears I don't have something right with my creds. Thoughts?

**Comment by Clancey** [comment]
That could be.  Getting that stuff right can be a pain.  How did you generate your secret? I have a section in the [readme](https://github.com/clancey/simpleauth#google-sign-in-on-android) on it.

**Comment by brittonbeckham** [comment]
Honestly, I read that like 3 times and I'm sorely confused at what to make. I already had a Web Application credential so I didn't make a new one. I made a new "App" credential and pulled the SHA1 signature from my signing key and put it in the there... don't know what I'm doing wrong ... or what I'm doing at all :)

**Comment by brittonbeckham** [comment]
Which clientId goes into the SimpleAuth ??? the Web Application one or the App one?

**Comment by Clancey** [comment]
You have to connect the web credentials with the app one.

**Comment by Clancey** [comment]
Pass in the Web ClientID/Secret.  The rest should auto work from the signing keys.

**Comment by Clancey** [comment]
Also they need to be in the same project. The Android and WebAPI should both be listed on the same tab [here](https://console.developers.google.com/apis/credentials).

**Comment by brittonbeckham** [comment]
That is what I have, but I don't think I got the right signing key... what is the keystore for debug mode? I used my production keystore and I dont' think that works. Super confused here, but thanks for helping me troubleshoot this.

![image](https://user-images.githubusercontent.com/7856371/31648276-0d37cbc0-b2ca-11e7-8949-8d11e74b47b2.png)

As you can see, I had the web application one created last year, and I just created the "Android" one today.

**Comment by Clancey** [comment]
So the key signing has to be right. When you created the android app, it asks for the fingerprint.  For debugging you can find information about the default keys [here](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/MD5_SHA1/) You can change the debug key and use your production key there.

**Comment by Clancey** [comment]
Also the default Xamarin Debug keys are different on every machine. So use your keys signing stuff.

**Comment by Clancey** [comment]
You will notice, I include the [keystore](https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Forms/Sample.Forms.Droid/SimpleAuth.keystore) to ensure it works for everyone testing. [CSProj using it for signing](https://github.com/Clancey/SimpleAuth/blob/master/samples/Sample.Forms/Sample.Forms.Droid/Sample.Forms.Droid.csproj#L39-L59)

**Comment by brittonbeckham** [comment]
Ok so does this mean I need to build my app with the same keystore when debugging and for production? Can I have two "app" in the google credentials store (one for dev and one for prod)?

**Comment by brittonbeckham** [comment]
Looks like that last piece of advice helped. I swapped out my debug configuration in my CSProj to just the product keystore file in the build... restarted the app and it worked! Thanks a lot!

**Comment by Clancey** [comment]
I would sign both Debug and Production the same.  As I said, default debug keys change per machine. Which would make things confusing as you switch dev machines and build servers.

**Comment by brittonbeckham** [comment]
Great point, I'll follow this approach.

One last thing. I'm not getting any UserData back in the account object. What would cause this?

**Comment by Clancey** [comment]
Using the native login the data you get back is limited.  However there is a convenience method: https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Providers/Google.cs#L123-L134

**Comment by brittonbeckham** [comment]
Perfect

**Comment by brittonbeckham** [comment]
Huge help today! Much thanks my friend.

**Comment by encrypt0r** [comment]
I have also observed that if there is no internet connection and the user has never signed in into the app, when the user clicks sign in a pop up shows all the users account but when he/she clicks on one of them it results in a `TaskCanceledException`. So make sure there is internet connection before signing in.

**Comment by axanth** [comment]
Hi there I am facing the same issue. Although it worked it suddenly started to throw this exception.
The things that changed are 1) I updated to the latest Packages Xamarin.Forms and SimpleAuth. and I created an Archive and publish the app as a Beta release to the store..... Is there a chance to be the sign issue you mentioned?? If yes can you be more specific about the solution steps? Thanks in advance
