### ISSUE TITLE
Nuget for Xamarin.Mac

### ISSUE THREAD

**Issue by dtaylorus** [Clancey/SimpleAuth#43]
I would find it very helpful to be able to install SimpleAuth for Xamarin.Mac via a nuget package.

**Comment by Clancey** [comment]
Already implemented: https://github.com/Clancey/SimpleAuth/blob/master/SimpleAuth.nuspec#L34

**Comment by dtaylorus** [comment]
That's great, thanks! But I can't find it on nuget.org. I'll open a separate issue for publishing it. :)

**Comment by Clancey** [comment]
It's right here: https://www.nuget.org/packages/Clancey.SimpleAuth/ No need to create a second issue.
