### ISSUE TITLE
Publish SimpleAuth.Mac nuget to nuget.org

### ISSUE THREAD

**Issue by dtaylorus** [Clancey/SimpleAuth#44]
It would be very helpful to have the SimpleAuth.Mac nuget package available on nuget.org. Thanks!

**Comment by Clancey** [comment]
There is no need to separate it out to it's own nuget package. It is available through the main nuget. https://www.nuget.org/packages/Clancey.SimpleAuth/

**Comment by dtaylorus** [comment]
I see. I'll give it a try. Thanks!

**Comment by dtaylorus** [comment]
For whatever reason, the nuget package does not have the namespace SimpleAuth.Providers. If I build the SimpleAuth.Mac project myself and reference the built binary, the namespace is there. At this point, I'll stop opening issues on the nuget package and just build it myself. Thanks for the quick responses!

**Comment by Clancey** [comment]
After installing the nuget try restarting the IDE. Also are you on the latest version of the Package? Feel free to open this issue if it working after the ide restart.
