### ISSUE TITLE
ResetData() and ResetClient() -- What do these methods do?

### ISSUE THREAD

**Issue by brittonbeckham** [Clancey/SimpleAuth#45]
Looking to "Sign out" my users... what is the best approach (not documentation available so I have to ask here). Thanks.

**Comment by Clancey** [comment]
It was originally called reset data. However I added [LogOut](https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Api/Api.cs#L95) a while ago since the name makes the most sense.
