### ISSUE TITLE
Xamarin.Forms iOS login with different user.

### ISSUE THREAD

**Issue by Asseks** [Clancey/SimpleAuth#46]
I've implemented Facebook login to XF project.
Login works good. I do logout: 
```
 SocialAuthApi = new FacebookApi("facebook", AppConstants.FacebookClientId, AppConstants.FacebookClientSecret);
 SocialAuthApi.ResetData();
 SocialAuthApi.Logout();

```
And after that I want to login by another user, but I can't do bcouz previous user was saved and facebook propose me log in with the same user. 
How I can log in by different user?

**Comment by Clancey** [comment]
Are you using the Native Facebook Api, or just the webview authentication?

**Comment by sergio11** [comment]
If you are using the Native Facebook Api through `Clancey.SimpleAuth.Facebook.Droid` Is it not possible to logout using ResetData?

I would need to implement this

**Comment by Asseks** [comment]
@sergio11 I've implemented LoginManager.Instance.Logout() method into my code. It's allows to login other users

**Comment by sergio11** [comment]
Could you tell me how I can do it please?

**Comment by sergio11** [comment]
In IOS it would be the same way?

**Comment by sergio11** [comment]
have you used this line only? . `LoginManager.Instance.LogOut ()` does not work for me;
