### ISSUE TITLE
Dropbox v2

### ISSUE THREAD

**Issue by TomQv** [Clancey/SimpleAuth#48]
SimpleAuth.Providers.DropBoxApi.cs is still on DropBox api v1, which doesn't work anymore.
I like SimpleAuth because its lean and slim without unnecessary dependencies, but  I need some help with the dropbox api  v2?

Thanks, Tom

**Comment by Clancey** [comment]
Nuget has been pushed with new api

**Comment by TomQv** [comment]
Thanks, but now the result is:

"We can't connect to the service you need right now. Check your network connection or try this again later"

testing with Sample.Forms.UWP:
CreateApiButton ( new DropBoxApi ( "Dropbox", "1s0______c5","vdf_______9j6")),

**Comment by Clancey** [comment]
Sorry UWP does need a little more love. Making sure the API's work there. The WebAuthenticationBroker isn't the best API :(

**Comment by Clancey** [comment]
This is most likely caused by a faulty Redirect URL. Dropbox doesn't handle that very well. It works for me as long as the Redirect matches perfectly.

**Comment by TomQv** [comment]
in DropBox.cs:

public DropBoxAuthenticator()
{
     RedirectUrl = new Uri("http://localhost");
}

this ends up in "http://localhost/". So I had to add the tailing "/" in my Dropbox-app config in RedirectUrl.
Now its fine.
