### ISSUE TITLE
Microsoft login with UWP, login window re-opens

### ISSUE THREAD

**Issue by TomQv** [Clancey/SimpleAuth#50]
After successful login to Microsoft, the login-windows closes, the token is returned in account, but then the login-window re-opens and must be closes again with cancel.

Testing with Sample.Forms.UWP,:

CreateApiButton ( new MicrosoftLiveConnectApi  ( "onedrive", "6243___246", "cmP____7+~}")
{
	Scopes =  new[] {  "onedrive.readwrite", "wl.signin"  },
}),

**Comment by Clancey** [comment]
I cannot duplicate this.

**Comment by TomQv** [comment]
I also have it with Android.

It comes from PrepareClient ->  VerifyCredentials() -> RefreshAccount() -> RefreshToken()
Result of the request is "invalid_request"

Maybe my Onedrive-credentials are wrong?

![2017_11_10_11_40_25_simpleauthtest_registration](https://user-images.githubusercontent.com/6605960/32652145-08b358a8-c60c-11e7-9c6e-bf720d6e9f04.png)

**Comment by TomQv** [comment]
looks like, it has todo with the scopes.
I had: 
"onedrive.readwrite", "wl.signin"

No I changed to:
"wl.signin", "wl.offline_access", "wl.skydrive_update"

And it works, no second window any more, all fine.
All this is very difficult....

**Comment by Clancey** [comment]
Ahh yes, Offline access is required for apps, if not they don't send refresh tokens.  Auth is hard. That's why I wrote this library. I simplified it as much as I can, but there is only so much I can do since it has to interact with third parties.
