### ISSUE TITLE
How to cancel Login dialog on Mac?

### ISSUE THREAD

**Issue by TomQv** [Clancey/SimpleAuth#53]
there is no cancel and the dialog also doesn't have the close-button.

**Comment by Clancey** [comment]
Yes, the mac presentation window needs a little bit of work. It is on my Todo list. Pull requests are welcomed ;)

**Comment by TomQv** [comment]
Thanks, thats fine now.

Just for information. To use OneDrive I had to add this key/value to the info.plist of the app, because during OneDrive auth there is a unsecure http call.

```
<key>NSAppTransportSecurity</key>
<string>NSAllowsArbitraryLoads</string>
```

**Comment by Clancey** [comment]
I actually don't ship a OneDrive Api. It must be something during your setup. However I do have a project that does authenticate against OneDrive. And it works just fine: https://github.com/Clancey/gMusic/blob/master/Api/OneDrive/OneDriveApi.cs
