### ISSUE TITLE
Implicit flow support?

### ISSUE THREAD

**Issue by kentcb** [Clancey/SimpleAuth#54]
Hi,

We're trying to use SimpleAuth against a back-end set up with implicit flow. We're able to successfully receive the auth token, but then [this line](https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/OAuth/OAuthApi.cs#L188) sends a request that the server refuses to serve ("invalid request" message). However, our theory is that this request shouldn't even be sent with the implicit flow.

Does SimpleAuth support an implicit flow?

Thanks

**Comment by Clancey** [comment]
Not out of the box, However it is super simple. Just override that method.  Similar to how Facebook Native works:  
https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Providers/Facebook.cs#L53-L61

I am guessing the token doesn't expire so set it to -1.

**Comment by kentcb** [comment]
Great, thanks - that's the approach we've been pursuing, so glad we're on the right track 👍
