### ISSUE TITLE
For ios11 NativeSafariAuthenticator should use SFAuthenticationSession

### ISSUE THREAD

**Issue by jasallen** [Clancey/SimpleAuth#57]
Apple is planning to start (and some say have already started) rejecting apps that do any OAuth with older methods (webview or SFSafariViewController)

**Comment by jasallen** [comment]
Had intended to work on ChromeTabs, but I see you've gotten that started.  I'll tackle and pull request this issue instead

**Comment by Clancey** [comment]
I haven't fully tested chrome tabs either. So feel free to take a look at what I did!

**Comment by jasallen** [comment]
https://github.com/Clancey/SimpleAuth/pull/58 <- SfAuthenticationSession 

I'll grab the chrome tab branch and take a look!
