### ISSUE TITLE
Status{statusCode=DEVELOPER_ERROR, resolution=null}

### ISSUE THREAD

**Issue by h0s** [Clancey/SimpleAuth#63]
Hello developers , please i face this problem and i searched over the day for a solution but no way 
System.Exception: Status{statusCode=DEVELOPER_ERROR, resolution=null} this error show after choosing google account , i searched and found that the sha1 and package name missmatching but all configuration are right 
result code is canceled (41221) aany help please !

**Comment by Clancey** [comment]
Are you using the native Google authenticator on Droid? Or just the built in web view?

**Comment by h0s** [comment]
i use xamarin forms , i used the native google authenticator on doid and using azure hub 
simply i try to implement this samples https://github.com/xamarin/Sport, i have my own backend that work and online singin work well but the problem related to the request.
i

**Comment by h0s** [comment]
is xamarin droid project , the exception here ;    SimpleAuth.Native.OnActivityResult(requestCode, resultCode, data);
requestcode 41221 and resultcode result.canceled

**Comment by h0s** [comment]
I resolved this problem, the apk file was signing using a different KeyStore that is in resource folder and not the KeyStore that I put in android proprieties project 
thank you  @Clancey for your time
