### ISSUE TITLE
SFAuthenticationSession doesn't seem to save account

### ISSUE THREAD

**Issue by baywolf-studios** [Clancey/SimpleAuth#64]
Running the authenticate method on the dropboxapi on android and on iOS 9 seems to save the account access token and other account info as calling it a second time doesn't prompt the user. But on iOS 11 with the SFAuthenticationSession it will present the safari view every time authenticate is called.

**Comment by Clancey** [comment]
On device or the simulator? You have to set entitlements on the simulator. Works without on device.

**Comment by baywolf-studios** [comment]
Yep, it’s on the simulator. Is there specific entitlements that need to be set for the simulator to function that way or does it only work on the device itself?

**Comment by Clancey** [comment]
Nothing special. Just under the iOS settings set the default entitlements file. That will force the device to sign it and it will work.

**Comment by baywolf-studios** [comment]
Awesome, thank you!
