### ISSUE TITLE
Facebook Authentication

### ISSUE THREAD

**Issue by rifletcher** [Clancey/SimpleAuth#67]
Hi, 

I'm trying to add Facebook Authentication to my Xamarin project. 

        public async Task<bool> LoginWithFacebookAsync()
        {
            var api = new FacebookApi("facebook", "", "");
            try
            {
                var account = await api.Authenticate();
            }
            catch (TaskCanceledException)
            {
                Console.WriteLine("Canceled");
                // todo
                //MainPage.DisplayAlert("Error", "User Canceled", "Ok");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                // todo
                //MainPage.DisplayAlert("Error", ex.Message, "Ok");
            }
            return true;
        }

An error is displayed in the facebook window "The parameter app_id is required". I've tried on UWP and Android. The sample project in SimpleAuth also gives the same message when using the facebook button.

What am I doing wrong?

**Comment by Clancey** [comment]
You need to register your app with Facebook, the second and third parameters are for the facebook clientid/client secret in the FacebookApi.  If you look at your code, you are passing in an empty string
