### ISSUE TITLE
Do Work it on Xamarin / Xamarin Forms only or also .NET platform like .NET Core or Asp.Net MVC/Core2?

### ISSUE THREAD

**Issue by biapar** [Clancey/SimpleAuth#68]
Do Work it on Xamarin / Xamarin Forms only or also .NET platform like .NET Core or Asp.Net MVC/Core2?

**Comment by Clancey** [comment]
It works on .net core. Depending on the interface you need to implement the Login Interface: [Sample](https://github.com/Clancey/Rosie/blob/76ceb64e8f1ce3b01d9d8346deaebe419e5fb7ba/Rosie.Server/Helpers/BasicAuthController.cs)

I have never tried/used it on Asp.net The code should compile, again you would need to handle the AuthControllers, and it may have state issues. But worth a try. IF you do get it working on asp.net I accept pull request.
