### ISSUE TITLE
Google native login not working

### ISSUE THREAD

**Issue by marufbd** [Clancey/SimpleAuth#70]
Clancey.SimpleAuth: 1.0.49
Clancey.SimpleAuth.Google.Droid: 1.0.9

This is my code
` var api = new GoogleApi("google",                
                "my_client_id",
                GoogleApi.NativeClientSecret) //native client secret only for Android
            {
                Scopes = scopes
            };

            try
            {
                OAuthAccount account = await api.Authenticate() as OAuthAccount;
                if (account != null)
                {

                }
                else
                {
                    await UserDialogs.Instance.AlertAsync("Login Failed!");
                }
            }
            catch (TaskCanceledException e)
            {
                await UserDialogs.Instance.AlertAsync($"canceled");
            }`

This shows the list of google accounts on my phone on ai.Authenticate() call, but after choosing any account always hits Task Canceled exception.

On my activity:
`protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);

            SimpleAuth.Native.OnActivityResult(requestCode, resultCode, data);
        }`

The requestCode is `41221` and resultData `Android.App.Result.Canceled`

Not sure if I am missing anything here.

**Comment by Clancey** [comment]
This is always caused by incorrect signing/secrets. Make but your are signing with the keys your setup for that secret.

**Comment by marufbd** [comment]
@Clancey, I guess you need to address this, google native login is broken on your source.
It seems google now entirely identifies the app through certificate hash and the package name which needs to be registered on gcloud console. The only requirement for app developer is to sign it with same key, no need to pass client id. 

In fact if you pass the client id like this:
`var gsoBuilder = new GoogleSignInOptions.Builder(GoogleSignInOptions.DefaultSignIn).RequestIdToken(clientID).RequestEmail();`

You will get this error:
`W/Auth: [GetToken] GetToken failed with status code: INVALID_AUDIENCE `
and this:
`E/TokenRequestor: You have wrong OAuth2 related configurations, please check. Detailed error: INVALID_AUDIENCE`

and in turn `TaskCanceledException`.

The fix is to remove the RequestIdToken or RequestServerAuthCode in the project SimpleAuth.Google.Droid:
`var gsoBuilder = new GoogleSignInOptions.Builder(GoogleSignInOptions.DefaultSignIn).RequestEmail();`

Hope you will check this out, #66 was probably related to same.

**Comment by snavatta** [comment]
@Clancey Hello, could you update the NuGet repo with this fix? Thanks.

**Comment by Clancey** [comment]
Nuget is updated!
