### ISSUE TITLE
Can’t Enter Password on Gear VR Version

### ISSUE THREAD

**Issue by WinkyJamie** [Clancey/SimpleAuth#73]
Hi there,

Due to the plugin holding the player’s camera completely in place, it appears to be blocking my ability to enter any text (such as to register or enter a password). I have both the SimpleAuth plugin and the helper plugin installed.

If you could please let me know what I should do to fix this, I’d really appreciate it!

Thanks so much,
Jamie

**Comment by Clancey** [comment]
I am not sure what helper plugin you installed. I don't have a VR grear to debug. I would suggest trying from the source of you can narrow it down I can see how I can help.

**Comment by Clancey** [comment]
Is everything working ok?
