### ISSUE TITLE
FitBit Droid CustomTabs just hangs

### ISSUE THREAD

**Issue by rpierry** [Clancey/SimpleAuth#77]
I'm using the FitBit provider in Xamarin Forms.  When I trigger the authentication, a browser pops up and I'm prompted to enter my fitbit credentials, but the tab just sits there and doesn't close afterwards.

I suspect that a redirect is happening but I haven't explicitly registered a scheme in my manifest (you don't have docs that say you need to do this).  I saw SimpleAuthCallbackActivity in the Droid.CustomTabs source, but it doesn't have an ActivityAttribute on it, so I'm not sure what name to use when putting the scheme/intent stuff in the manifest (if that is in fact what I'm supposed to do).

Thanks!

**Comment by rpierry** [comment]
I solved my own problem.

I went into obj/Debug/android/src and found the folder that contained SimpleAuthCallbackActivity.java.  I then added the following to my androidmanifest.xml: (obviously replace the md5 bit with the folder you find this in)

<activity android:name="md5089048e4802c0ad89daddc8855d8a7f0.SimpleAuthCallbackActivity" >
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myscheme" />
      </intent-filter>
    </activity>

Maybe consider this issue a request for documentation on the customtab stuff.

Thanks for providing this package!

**Comment by Clancey** [comment]
I agree, It needs documentation. I have a gist: https://gist.github.com/Clancey/630afc3021f563468fda88c29e892aa6 . That is a simpler way than modifying the android manifest.  If you are interested in sending a pull request for the documentation, I would accept it!
