### ISSUE TITLE
How to refresh Google token?

### ISSUE THREAD

**Issue by Lemedon** [Clancey/SimpleAuth#81]
Hi! How can I refresh google access token without prompting native google account dialog? 
Thanks :)

**Comment by Clancey** [comment]
You need a client secret to never show the login page again. If you pass it in the constructor, simple auth can refresh auth tokens all on its own.

**Comment by Lemedon** [comment]
How can I get client secret? I am only able to see client_id at console.developers.google.com.

**Comment by Clancey** [comment]
You can create a web/server credentials to go with the mobile app.

**Comment by Lemedon** [comment]
This method does not work. It's throw same exception as mentioned in #75
