### ISSUE TITLE
Sample.forms

### ISSUE THREAD

**Issue by mdonogma** [Clancey/SimpleAuth#83]
Xamarin forms supports Xamarin.mac now.

Will this work with Xamarin.forms Mac apps? Example please as I’m tired of struggling to get oath working in this scenarion

**Comment by Clancey** [comment]
It just works. Add they nugget make API calls. It will automatically present the login UI.

**Comment by mdonogma** [comment]
question: where is the nuspec for SimpleAuth.Mac? or which Nugget package are you referring to?

**Comment by Clancey** [comment]
There is only one nugget. It contains all the targets. The additional libraries are iOS and Android only since they're using additional iOS/Android libraries.
