### ISSUE TITLE
Xamarin.mac facebook login dialog doesn't show correctly

### ISSUE THREAD

**Issue by mdonogma** [Clancey/SimpleAuth#88]
doesn't render correctly - should fit the way the iOS implementation does.

buttons and entry fields are outside of visible area.
<img width="397" alt="image" src="https://user-images.githubusercontent.com/13458476/52942328-86320400-33b6-11e9-9605-4f98b2aa538e.png">

**Comment by Clancey** [comment]
This is an issue on facebooks side. They should be adjusting the pager to fit. I am guessing you are using the web authenticator. 
https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth.Mac/WebAuthenticator.cs#L176. You can always present it a different way with different values.
