### ISSUE TITLE
Anyway to logout social login? e.g. clean webview cookie?

### ISSUE THREAD

**Issue by jamesatgithub** [Clancey/SimpleAuth#9]
it seems remembered the login

**Comment by Clancey** [comment]
Yes, Call ResetData on the API class. https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth/Api/Api.cs#L79

**Comment by Clancey** [comment]
You can also specify ClearCookies on the authenticator. OAuth Api does this for you doing a reset:
https://github.com/Clancey/SimpleAuth/blob/dd350674c52d832e87284d8554d6624ed194b30b/src/SimpleAuth/OAuth/OAuthApi.cs#L93

**Comment by jamesatgithub** [comment]
Thanks. 
It would be good there is a static method to clean the cookies as when logout the api instance may not exist

**Comment by Clancey** [comment]
It shouldn't be static as it would interfere with other APIs. What my long term plan is bundle the cookies with the API so they are always cleared and then reloaded with the cookies from that API. Just haven't gotten to it yet.

**Comment by jamesatgithub** [comment]
Ok good to know the plan. in my case when logging out, since api instance isn't available, I had to instantiate a fake TwitterApi with empty clientid/scerent, then call its ResetData method

**Comment by Clancey** [comment]
I just pushed this update that makes cookies in the web views per api.  Would you mind kicking the tires? I checked it on iOS, but not a lot on Android

**Comment by jamesatgithub** [comment]
just did a test on Android with facebook it works. Thanks if any issue found, will raise here

**Comment by jamesatgithub** [comment]
just did testing with 1.0.21 with Android, the auth cookie is still saved for Twitter and Google login - had to use the ResetData for now

**Comment by jamesatgithub** [comment]
Google/Twitter/Facebook works on ios

**Comment by Clancey** [comment]
Data is saved by the identifier passed into the API. As long you use the same identifier, it will remember you.

**Comment by jamesatgithub** [comment]
hmm so in my case I still need use ResetData, as I was just needing a logout feature for social login

**Comment by Clancey** [comment]
Yes reset data is the same as log out. I have considered renaming it. But as you noticed simple auth keeps you logged in automatically. Which makes sense for most apps.

**Comment by allan-chin** [comment]
I'm building a Windows UWP application performing a Google authentication. SimpleApi is authenticating fine thank you, but I would like to logout at app termination. I've attempted to call ResetData() and LogOut(), but both throw this exception...

**The parameter is incorrect. Cannot create credential.**

How can I force the logout?

Thanks.

**Comment by allan-chin** [comment]
I found out why the Exception is thrown on Logout. From the following code, on Logout, "pass" is removed from the vault correctly, but the last line tries to re-add the credential for some reason. And on Logout, "value" is empty. Seems like that line should be in the else clause for "if (pass != null)".

		public void SetSecured(string id, string value, string clientId, string service, string sharedGroup)
		{
			var vault = new Windows.Security.Credentials.PasswordVault();
			try
			{
				var pass = vault.Retrieve(ResourceIdentifier, $"{clientId}-{id}-{service}");
				if (pass != null)
					vault.Remove(pass);
			}
			catch { }
			vault.Add(new Windows.Security.Credentials.PasswordCredential(ResourceIdentifier, $"{clientId}-{id}-{service}", value));
		}
`

**Comment by Clancey** [comment]
Would you mind sending a pull request?

**Comment by Clancey** [comment]
Actually that code should work, what it does is check if there is a value for that key, if so remove it. 

Adding a key with a null value should be fine? Unless that crashes which I have no idea why it would...

If you wanted to wrap https://github.com/Clancey/SimpleAuth/blob/master/src/SimpleAuth.UWP/AuthStorage.cs#L35 in
```
if(!String.IsNullOrWhitepace(value)) {
	vault.Add(new Windows.Security.Credentials.PasswordCredential(ResourceIdentifier, $"{clientId}-{id}-{service}", value));
}
```
That would be fine as well

**Comment by allan-chin** [comment]
Interesting. What is doing the checking in the original code? The PasswordCredential constructor? Here's what I get running the Sample.Forms.UWP. I hope this helps.

![simpleauth](https://user-images.githubusercontent.com/30632583/59464362-14eee480-8ddd-11e9-844e-6c94af2d04e5.png)

Thanks for you quick response.

**Comment by Clancey** [comment]
Do you want to try it with doing a it with the code I wrote in above?  And if that fixes it, just send a pull request!

**Comment by allan-chin** [comment]
Works great! I've created a new pull request with the fix, and I included some of my code which adds a Logout button to test.

Thanks for maintain this library.
